name: Publish to pub.dev

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# Publish using the reusable workflow from dart-lang
jobs:
  publish:
    name: Publish to pub.dev
    environment: pub.dev
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup Dart SDK with JWT token
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true
      # Minimal package setup and dry run checks
      - name: Install dependencies
        run: flutter pub get
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46 
      - name: Dry run 
        run: dart pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f

  create_release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }}
